# -*- coding: utf-8 -*-

import names

def main():
    test.log("Test Wifi Settings")

    startApplication("ui")
    setWindowState(waitForObject(names.o_MainWindow), WindowState.Maximize)
    test.vp("VP1")
    mouseClick(waitForObject(names.o_Sidebar), 169, 102, Qt.NoModifier, Qt.LeftButton)
    clickButton(waitForObject(names.network_QPushButton))
    test.imagePresent("image_2")
    clickButton(waitForObject(names.advanced_btn_QPushButton))

    clickButton(waitForObject(names.eDIT_QPushButton))

    test.vp("VP12")
    clickButton(waitForObject(names.o_KeyButton_14))
    clickButton(waitForObject(names.o_KeyButton_14))
    doubleClick(waitForObject(names.o_KeyButton_14), 97, 54, Qt.NoModifier, Qt.LeftButton)
    clickButton(waitForObject(names.o_KeyButton_14))
    clickButton(waitForObject(names.o_KeyButton_14))
    doubleClick(waitForObject(names.o_KeyButton_14), 97, 54, Qt.NoModifier, Qt.LeftButton)
    doubleClick(waitForObject(names.o_KeyButton_14), 97, 54, Qt.NoModifier, Qt.LeftButton)
    clickButton(waitForObject(names.o_KeyButton_14))
    doubleClick(waitForObject(names.o_KeyButton_14), 97, 54, Qt.NoModifier, Qt.LeftButton)
    clickButton(waitForObject(names.o_QPushButton_2))
    clickButton(waitForObject(names.s_KeyButton))
    clickButton(waitForObject(names.w_KeyButton))
    clickButton(waitForObject(names.a_KeyButton))
    clickButton(waitForObject(names.g_KeyButton))
    clickButton(waitForObject(names.s_KeyButton))
    clickButton(waitForObject(names.w_KeyButton))
    clickButton(waitForObject(names.a_KeyButton))
    clickButton(waitForObject(names.g_KeyButton))
    clickButton(waitForObject(names.c_KeyButton))
    clickButton(waitForObject(names.o_KeyButton))
    doubleClick(waitForObject(names.m_KeyButton), 82, 47, Qt.NoModifier, Qt.LeftButton)
    clickButton(waitForObject(names.a_KeyButton))
    clickButton(waitForObject(names.o123_KeyButton))
    clickButton(waitForObject(names.o_KeyButton_2))
    test.vp("VP13")
    clickButton(waitForObject(names.o_KeyButton_13))
    test.vp("VP14")

    clickButton(waitForObject(names.aDD_QPushButton))
    test.vp("VP15")
    
    clickButton(waitForObject(names.o123_KeyButton))
    clickButton(waitForObject(names.o_KeyButton_16))
    clickButton(waitForObject(names.o_KeyButton_17))
    clickButton(waitForObject(names.o_KeyButton_15))
    clickButton(waitForObject(names.o_KeyButton_18))
    clickButton(waitForObject(names.o_KeyButton_19))
    clickButton(waitForObject(names.o_KeyButton_20))
    sendEvent("QMouseEvent", waitForObject(names.o_KeyButton_13), QEvent.MouseButtonPress, 140, 73, Qt.LeftButton, 1, 0)
    sendEvent("QMouseEvent", waitForObject(names.o_KeyButton_13), QEvent.MouseButtonRelease, 321, -223, Qt.LeftButton, 0, 0)
    clickButton(waitForObject(names.o_KeyButton_13))
    test.vp("VP16")
    clickButton(waitForObject(names.confirm_btn_QPushButton))
    test.vp("VP17")
    
    sendEvent("QWheelEvent", waitForObject(names.o_ListWidget), 296, 411, -35, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.o_ListWidget), 296, 428, -31, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_SSH_QPushButton), 296, 9, -94, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_SSH_QPushButton), 296, 56, -35, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_SSH_QPushButton), 296, 73, -35, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_SSH_QPushButton), 296, 91, -35, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_SSH_QPushButton), 296, 108, -38, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.o_ListWidget), 296, 562, -35, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.sSH_Keys_QPushButton), 296, 0, -35, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.sSH_Keys_QPushButton), 296, 17, -31, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.sSH_Keys_QPushButton), 296, 33, -35, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.sSH_Keys_QPushButton), 296, 50, -31, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.sSH_Keys_QPushButton), 296, 66, -35, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.sSH_Keys_QPushButton), 296, 83, -31, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.sSH_Keys_QPushButton), 296, 99, -24, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.sSH_Keys_QPushButton), 296, 111, -28, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.o_ListWidget), 296, 705, -24, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.o_ListWidget), 296, 717, -24, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 4, -24, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 16, -21, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -24, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -21, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -24, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -28, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -28, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -24, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -21, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -21, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -21, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -17, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -17, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -17, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -17, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -21, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -21, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -24, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -24, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -31, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -31, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -28, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -28, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -31, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -28, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -24, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -24, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -24, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -21, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -14, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -17, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -14, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -14, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -10, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -10, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -7, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -3, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.enable_Roaming_QPushButton), 296, 23, -3, 0, 2)
    test.vp("VP30")    
    
