# -*- coding: utf-8 -*-

import names

def main():
    test.log("Testing Training Guide")

    startApplication("ui")
    test.vp("VP1")
    mouseClick(waitForObject(names.o_Sidebar), 188, 101, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP2")
    sendEvent("QWheelEvent", waitForObject(names.driver_Camera_QPushButton), 250, 83, -31, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.driver_Camera_QPushButton), 250, 98, -28, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.driver_Camera_QPushButton), 250, 112, -28, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.o_DevicePanel), 300, 491, -24, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.o_DevicePanel), 300, 503, -24, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.o_DevicePanel), 300, 515, -35, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.o_DevicePanel), 300, 533, -38, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 17, -49, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 41, -56, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 69, -45, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 92, -45, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -35, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -35, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -38, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -42, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -38, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -42, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -35, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -38, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -31, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -35, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -42, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -42, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -42, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -42, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -38, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -35, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -31, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -28, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -35, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -31, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -35, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -35, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -31, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -35, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -35, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -42, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -45, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -63, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -52, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -45, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -42, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -42, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -49, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -45, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -45, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -38, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -28, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -24, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -24, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -14, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -14, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -10, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.reset_Calibration_QPushButton), 250, 105, -7, 0, 2)
    clickButton(waitForObject(names.rEVIEW_QPushButton))
    test.vp("VP5")
    clickButton(waitForObject(names.confirm_btn_QPushButton))
    test.vp("VP6")
    mouseClick(waitForObject(names.o_TrainingGuide), 392, 810, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP7")
    mouseClick(waitForObject(names.o_TrainingGuide), 1227, 326, Qt.NoModifier, Qt.LeftButton)
    mouseClick(waitForObject(names.o_TrainingGuide), 1719, 479, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP8")
    mouseClick(waitForObject(names.o_TrainingGuide), 1698, 462, Qt.NoModifier, Qt.LeftButton)
    sendEvent("QWheelEvent", waitForObject(names.o_TrainingGuide), 1805, 123, 24, 0, 1)
    sendEvent("QWheelEvent", waitForObject(names.o_TrainingGuide), 1805, 123, 31, 0, 1)
    sendEvent("QWheelEvent", waitForObject(names.o_TrainingGuide), 1805, 123, 17, 0, 1)
    sendEvent("QWheelEvent", waitForObject(names.o_TrainingGuide), 1805, 123, 14, 0, 1)
    sendEvent("QWheelEvent", waitForObject(names.o_TrainingGuide), 1805, 123, 7, 0, 1)
    sendEvent("QWheelEvent", waitForObject(names.o_TrainingGuide), 1800, 123, -28, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.o_TrainingGuide), 1800, 123, -49, 0, 1)
    sendEvent("QWheelEvent", waitForObject(names.o_TrainingGuide), 1800, 123, -42, 0, 1)
    sendEvent("QWheelEvent", waitForObject(names.o_TrainingGuide), 1800, 123, -49, 0, 1)
    sendEvent("QWheelEvent", waitForObject(names.o_TrainingGuide), 1800, 123, -66, 0, 1)
    sendEvent("QWheelEvent", waitForObject(names.o_TrainingGuide), 1800, 123, -52, 0, 1)
    sendEvent("QWheelEvent", waitForObject(names.o_TrainingGuide), 1800, 123, -38, 0, 1)
    sendEvent("QWheelEvent", waitForObject(names.o_TrainingGuide), 1800, 123, -38, 0, 1)
    sendEvent("QWheelEvent", waitForObject(names.o_TrainingGuide), 1800, 123, -31, 0, 1)
    sendEvent("QWheelEvent", waitForObject(names.o_TrainingGuide), 1800, 123, -17, 0, 1)
    sendEvent("QWheelEvent", waitForObject(names.o_TrainingGuide), 1800, 123, -14, 0, 1)
    test.vp("VP9")
    mouseClick(waitForObject(names.o_TrainingGuide), 1528, 550, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP10")
    mouseClick(waitForObject(names.o_TrainingGuide), 1525, 547, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP11")
    mouseClick(waitForObject(names.o_TrainingGuide), 1737, 499, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP12")
    mouseClick(waitForObject(names.o_TrainingGuide), 1662, 653, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP13")
    mouseClick(waitForObject(names.o_TrainingGuide), 1410, 369, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP14")
    mouseClick(waitForObject(names.o_TrainingGuide), 1535, 547, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP15")
    mouseClick(waitForObject(names.o_TrainingGuide), 840, 809, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP16")
    mouseClick(waitForObject(names.o_TrainingGuide), 1484, 395, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP17")
    mouseClick(waitForObject(names.o_TrainingGuide), 1745, 503, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP18")
    mouseClick(waitForObject(names.o_TrainingGuide), 1704, 685, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP19")
    mouseClick(waitForObject(names.o_TrainingGuide), 1712, 457, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP20")
    mouseClick(waitForObject(names.o_TrainingGuide), 1501, 392, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP21")
    mouseClick(waitForObject(names.o_TrainingGuide), 1356, 558, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP22")
    mouseClick(waitForObject(names.o_TrainingGuide), 1724, 494, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP23")
    mouseClick(waitForObject(names.o_TrainingGuide), 1721, 493, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP24")
    mouseClick(waitForObject(names.o_TrainingGuide), 820, 790, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP25")

