# encoding: UTF-8

from objectmaphelper import *

o_MainWindow = {"type": "MainWindow", "unnamed": 1, "visible": 1}
o_Sidebar = {"type": "Sidebar", "unnamed": 1, "visible": 1, "window": o_MainWindow}
o_QPushButton = {"text": "×", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
driver_Camera_QPushButton = {"text": "Driver Camera", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
o_DevicePanel = {"type": "DevicePanel", "unnamed": 1, "visible": 1, "window": o_MainWindow}
reset_Calibration_QPushButton = {"text": "Reset Calibration", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
review_Training_Guide_QPushButton = {"text": "Review Training Guide", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
o_SettingsWindow = {"type": "SettingsWindow", "unnamed": 1, "visible": 1, "window": o_MainWindow}
change_Language_QPushButton = {"text": "Change Language", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
network_QPushButton = {"text": "Network", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
ssidLabel_ElidedLabel = {"name": "ssidLabel", "occurrence": 2, "type": "ElidedLabel", "visible": 1, "window": o_MainWindow}
o_ListWidget = {"type": "ListWidget", "unnamed": 1, "visible": 1, "window": o_MainWindow}
advanced_btn_QPushButton = {"name": "advanced_btn", "type": "QPushButton", "visible": 1, "window": o_MainWindow}
iP_Address_QPushButton = {"text": "IP Address", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
enable_SSH_QPushButton = {"text": "Enable SSH", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
sSH_Keys_QPushButton = {"text": "SSH Keys", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
o_Toggle = {"type": "Toggle", "unnamed": 1, "visible": 1, "window": o_MainWindow}
o_Toggle_2 = {"occurrence": 2, "type": "Toggle", "unnamed": 1, "visible": 1, "window": o_MainWindow}
aDD_QPushButton = {"text": "ADD", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
o_InputDialog = {"type": "InputDialog", "unnamed": 1, "visible": 1}
q_KeyButton = {"text": "q", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
w_KeyButton = {"text": "w", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
e_KeyButton = {"text": "e", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
r_KeyButton = {"text": "r", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
t_KeyButton = {"text": "t", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
y_KeyButton = {"text": "y", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
u_KeyButton = {"text": "u", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
i_KeyButton = {"text": "i", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_KeyButton = {"text": "o", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
p_KeyButton = {"text": "p", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o123_KeyButton = {"text": 123, "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o1_KeyButton = {"text": 1, "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o2_KeyButton = {"text": 2, "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o3_KeyButton = {"text": 3, "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o4_KeyButton = {"text": 4, "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o5_KeyButton = {"text": 5, "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o6_KeyButton = {"text": 6, "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o7_KeyButton = {"text": 7, "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o8_KeyButton = {"text": 8, "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o9_KeyButton = {"text": 9, "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o0_KeyButton = {"text": 0, "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_KeyButton_2 = {"text": "#+=", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_KeyButton_3 = {"text": "[", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_KeyButton_4 = {"text": "]", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_KeyButton_5 = {"text": "{", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_KeyButton_6 = {"text": "}", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_KeyButton_7 = {"text": "#", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_KeyButton_8 = {"text": "%", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_KeyButton_9 = {"text": "^", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_KeyButton_10 = {"text": "*", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_KeyButton_11 = {"text": "+", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_KeyButton_12 = {"text": "=", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_KeyButton_13 = {"text": "→", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_ConfirmationDialog = {"type": "ConfirmationDialog", "unnamed": 1, "visible": 1}
confirm_btn_QPushButton = {"name": "confirm_btn", "type": "QPushButton", "visible": 1, "window": o_ConfirmationDialog}
reboot_btn_QPushButton = {"name": "reboot_btn", "type": "QPushButton", "visible": 1, "window": o_MainWindow}
cancel_QPushButton = {"text": "Cancel", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_ConfirmationDialog}
rEVIEW_QPushButton = {"text": "REVIEW", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
o_TrainingGuide = {"type": "TrainingGuide", "unnamed": 1, "visible": 1, "window": o_MainWindow}
eDIT_QPushButton = {"text": "EDIT", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
o_QPushButton_2 = {"occurrence": 2, "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_KeyButton_14 = {"text": "⌫", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_SshToggle = {"type": "SshToggle", "unnamed": 1, "visible": 1, "window": o_MainWindow}
o_KeyButton_15 = {"text": ":", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
cancel_QPushButton_2 = {"text": "Cancel", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
s_KeyButton = {"text": "s", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
a_KeyButton = {"text": "a", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
g_KeyButton = {"text": "g", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
c_KeyButton = {"text": "c", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
m_KeyButton = {"text": "m", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_KeyButton_16 = {"text": "-", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_KeyButton_17 = {"text": "/", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_KeyButton_18 = {"text": ";", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_KeyButton_19 = {"text": "(", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_KeyButton_20 = {"text": ")", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
enable_Roaming_QPushButton = {"text": "Enable Roaming", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
eDIT_QPushButton_2 = {"occurrence": 2, "text": "EDIT", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
l_KeyButton = {"text": "l", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
n_KeyButton = {"text": "n", "type": "KeyButton", "unnamed": 1, "visible": 1, "window": o_InputDialog}
o_PairingPopup = {"type": "PairingPopup", "unnamed": 1, "visible": 0}
rEMOVE_QPushButton = {"text": "REMOVE", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
aPN_Setting_QPushButton = {"text": "APN Setting", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
toggles_QPushButton = {"text": "Toggles", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
enable_Lane_Departure_Warnings_QPushButton = {"text": "Enable Lane Departure Warnings", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
o_TogglesPanel = {"type": "TogglesPanel", "unnamed": 1, "visible": 1, "window": o_MainWindow}
record_and_Upload_Driver_Camera_QPushButton = {"text": "Record and Upload Driver Camera", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
use_Metric_System_QPushButton = {"text": "Use Metric System", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
o_ButtonParamControl = {"type": "ButtonParamControl", "unnamed": 1, "visible": 1, "window": o_MainWindow}
standard_QPushButton = {"text": "Standard", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
o_body_h2_style_text_align_center_Experimental_Mode_h2_br_p_style_text_align_center_margin_0_128px_font_size_50px_openpilot_defaults_to_driving_in_b_chill_mode_b_Experimental_mode_enables_b_alpha_level_features_b_that_aren_t_ready_for_chill_mode_Experimental_features_are_listed_below_br_h4_End_to_End_Longitudinal_Control_h4_br_Let_the_driving_model_control_the_gas_and_brakes_openpilot_will_drive_as_it_thinks_a_human_would_including_stopping_for_red_lights_and_stop_signs_Since_the_driving_model_decides_the_speed_to_drive_the_set_speed_will_only_act_as_an_upper_bound_This_is_an_alpha_quality_feature_mistakes_should_be_expected_br_h4_Navigate_on_openpilot_h4_br_When_navigation_has_a_destination_openpilot_will_input_the_map_information_into_the_model_This_provides_useful_context_for_the_model_and_allows_openpilot_to_keep_left_or_right_appropriately_at_forks_exits_Lane_change_behavior_is_unchanged_and_still_activated_by_the_driver_This_is_an_alpha_quality_feature_mistakes_should_be_expected_particularly_around_exits_and_forks_These_mistakes_can_include_unintended_laneline_crossings_late_exit_taking_driving_towards_dividing_barriers_in_the_gore_areas_etc_br_h4_New_Driving_Visualization_h4_br_The_driving_visualization_will_transition_to_the_road_facing_wide_angle_camera_at_low_speeds_to_better_show_some_turns_The_Experimental_mode_logo_will_also_be_shown_in_the_top_right_corner_When_a_navigation_destination_is_set_and_the_driving_model_is_using_it_as_input_the_driving_path_on_the_map_will_turn_green_p_body_QLabel = {"text": "<body><h2 style=\"text-align: center;\">Experimental Mode</h2><br><p style=\"text-align: center; margin: 0 128px; font-size: 50px;\">openpilot defaults to driving in <b>chill mode</b>. Experimental mode enables <b>alpha-level features</b> that aren't ready for chill mode. Experimental features are listed below:<br><h4>End-to-End Longitudinal Control</h4><br>Let the driving model control the gas and brakes. openpilot will drive as it thinks a human would, including stopping for red lights and stop signs. Since the driving model decides the speed to drive, the set speed will only act as an upper bound. This is an alpha quality feature; mistakes should be expected.<br><h4>Navigate on openpilot</h4><br>When navigation has a destination, openpilot will input the map information into the model. This provides useful context for the model and allows openpilot to keep left or right appropriately at forks/exits. Lane change behavior is unchanged and still activated by the driver. This is an alpha quality feature; mistakes should be expected, particularly around exits and forks. These mistakes can include unintended laneline crossings, late exit taking, driving towards dividing barriers in the gore areas, etc.<br><h4>New Driving Visualization</h4><br>The driving visualization will transition to the road-facing wide-angle camera at low speeds to better show some turns. The Experimental mode logo will also be shown in the top right corner. When a navigation destination is set and the driving model is using it as input, the driving path on the map will turn green.</p></body>", "type": "QLabel", "unnamed": 1, "visible": 1, "window": o_ConfirmationDialog}
eXPERIMENTAL_MODE_ON_QLabel = {"text": "EXPERIMENTAL MODE ON", "type": "QLabel", "unnamed": 1, "visible": 1, "window": o_MainWindow}
eXPERIMENTAL_MODE_ON_QLabel_2 = {"leftWidget": eXPERIMENTAL_MODE_ON_QLabel, "type": "QLabel", "unnamed": 1, "visible": 1, "window": o_MainWindow}
openpilot_defaults_to_driving_in_b_chill_mode_b_Experimental_mode_enables_b_alpha_level_features_b_that_aren_t_ready_for_chill_mode_Experimental_features_are_listed_below_br_h4_End_to_End_Longitudinal_Control_h4_br_Let_the_driving_model_control_the_gas_and_brakes_openpilot_will_drive_as_it_thinks_a_human_would_including_stopping_for_red_lights_and_stop_signs_Since_the_driving_model_decides_the_speed_to_drive_the_set_speed_will_only_act_as_an_upper_bound_This_is_an_alpha_quality_feature_mistakes_should_be_expected_br_h4_Navigate_on_openpilot_h4_br_When_navigation_has_a_destination_openpilot_will_input_the_map_information_into_the_model_This_provides_useful_context_for_the_model_and_allows_openpilot_to_keep_left_or_right_appropriately_at_forks_exits_Lane_change_behavior_is_unchanged_and_still_activated_by_the_driver_This_is_an_alpha_quality_feature_mistakes_should_be_expected_particularly_around_exits_and_forks_These_mistakes_can_include_unintended_laneline_crossings_late_exit_taking_driving_towards_dividing_barriers_in_the_gore_areas_etc_br_h4_New_Driving_Visualization_h4_br_The_driving_visualization_will_transition_to_the_road_facing_wide_angle_camera_at_low_speeds_to_better_show_some_turns_The_Experimental_mode_logo_will_also_be_shown_in_the_top_right_corner_When_a_navigation_destination_is_set_and_the_driving_model_is_using_it_as_input_the_driving_path_on_the_map_will_turn_green_QLabel = {"text": "openpilot defaults to driving in <b>chill mode</b>. Experimental mode enables <b>alpha-level features</b> that aren't ready for chill mode. Experimental features are listed below:<br><h4>End-to-End Longitudinal Control</h4><br>Let the driving model control the gas and brakes. openpilot will drive as it thinks a human would, including stopping for red lights and stop signs. Since the driving model decides the speed to drive, the set speed will only act as an upper bound. This is an alpha quality feature; mistakes should be expected.<br><h4>Navigate on openpilot</h4><br>When navigation has a destination, openpilot will input the map information into the model. This provides useful context for the model and allows openpilot to keep left or right appropriately at forks/exits. Lane change behavior is unchanged and still activated by the driver. This is an alpha quality feature; mistakes should be expected, particularly around exits and forks. These mistakes can include unintended laneline crossings, late exit taking, driving towards dividing barriers in the gore areas, etc.<br><h4>New Driving Visualization</h4><br>The driving visualization will transition to the road-facing wide-angle camera at low speeds to better show some turns. The Experimental mode logo will also be shown in the top right corner. When a navigation destination is set and the driving model is using it as input, the driving path on the map will turn green.", "type": "QLabel", "unnamed": 1, "visible": 1, "window": o_MainWindow}
software_QPushButton = {"text": "Software", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_MainWindow}
